name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  infrastructure-setup:
    name: Infrastructure-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          command: |
            destroy
          pulumi-version: "^3.5.0" # Specify the desired version of Pulumi
          stack-name: dev # When using an individual account, only use stack-name.
          expect-no-changes: true # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
