name: Pulumi-Ecs-Setup
on:
  push:
    branches:
      - main
jobs:
  infrastructure-setup:
    name: Infrastructure-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com/ | bash
          export PATH=$PATH:$HOME/.pulumi/bin
      - name: Pulumi Login
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          pip install -r requirements.txt
          python3 -m venv env
          source env/bin/activate
          pulumi stack select dev
          pulumi preview
          pulumi destroy --yes
          
      # - name: Install Pulumi
      #   run: |

      #   with:
      #     command: |
      #       up
      #     pulumi-version: "^3.5.0" # Specify the desired version of Pulumi
      #     stack-name: dev # When using an individual account, only use stack-name.
      #     expect-no-changes: true # When using an individual account, only use stack-name.
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

# name: Pulumi
# on:
#   push:
#     branches:
#       - main
# jobs:
#   infrastructure-setup:
#     name: Infrastructure-setup
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-region: ${{ secrets.AWS_REGION }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       - run: |
#           pip install -r requirements.txt
#       - uses: pulumi/actions@v3
#         with:
#           command: |
#             destroy
#           pulumi-version: "^3.5.0" # Specify the desired version of Pulumi
#           stack-name: dev # When using an individual account, only use stack-name.
#           expect-no-changes: true # When using an individual account, only use stack-name.
#         env:
#           PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


  # Cypress-Test:
   
  
  #   name: Build Docker Image
  #   runs-on: ubuntu-latest  
  #   steps:  
  #       - name: Checkout
  #         uses: actions/checkout@v2    
          

  #       - name: Login to Amazon ECR
  #         id: login-pf-aws-ecr
  #         uses: aws-actions/amazon-ecr-login@v1
          

  #       - name: Build and push the tagged docker image to Amazon ECR
  #         env:
  #           ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
  #           ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
  #           IMAGE_TAG: latest
  #         run: |
  #           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  #           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
